#!/usr/bin/env node
/**
 * 把 tsc 的 CommonJS 客户端构建包进 DSH client-modules bundle。
 *
 * DSH 客户端加载器调用 `window.__ModuleLoader__.load({ id, factory })`；
 * 物化时执行 `factory(require)` 并把其返回值当作模块导出。本脚本把
 * tsc 产出的每个相对模块内联进一个闭包，把相对 `require("./x")` 改写为
 * 查本地表，裸说明符（react、react/jsx-runtime、@deepseek-ai/* 等）原样
 * 交给外层 require —— 浏览器模块表。
 */
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const out = join(root, 'lib')
const build = join(root, '.client-build')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const id = pkg.name

// 1. 收集产物模块，键 = 相对构建根的 forward-slash 路径（如 "index.js"）。
const modules = new Map()
const walk = (dir) => {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) walk(full)
    else if (entry.endsWith('.js')) {
      const key = relative(build, full).split('\\').join('/')
      modules.set(key, readFileSync(full, 'utf8'))
    }
  }
}
walk(build)

if (!modules.has('index.js')) throw new Error(`build-client: missing index.js in ${build}`)

// 2. 相对说明符 → 表内规范键（去 ./ 与扩展名，补 .js）。
const canonical = (spec, fromKey) => {
  const parts = []
  for (const seg of spec.split('/')) {
    if (seg === '.' || seg === '') continue
    if (seg === '..') parts.pop()
    else parts.push(seg)
  }
  const base = fromKey.includes('/') ? fromKey.slice(0, fromKey.lastIndexOf('/')) : ''
  const rel = (base ? base + '/' : '') + parts.join('/')
  return rel.replace(/\.(ts|tsx|js|jsx)$/, '') + '.js'
}

// 3. 改写每个模块体内的相对 require。
const rewrite = (body, fromKey) =>
  body.replace(/require\(\s*(['"])(\.{1,2}\/[^'"]*)\1\s*\)/g, (_, _q, spec) => {
    const target = canonical(spec, fromKey)
    if (!modules.has(target)) throw new Error(`build-client: unresolved local require ${spec} from ${fromKey}`)
    return `require(${JSON.stringify(target)})`
  })

const bodies = {}
for (const [key, body] of modules) {
  bodies[key] = rewrite(body, key)
}

// 4. 生成包装。
const tableEntries = Object.entries(bodies)
  .map(([key, body]) => `  ${JSON.stringify(key)}: function (module, exports, require) {\n${body.replace(/^/gm, '    ')}\n  }`)
  .join(',\n')

const bundle = `/* ${id} client bundle (generated by scripts/build-client.mjs) */
window.__ModuleLoader__.load({
  id: ${JSON.stringify(id)},
  factory: function (require) {
    var __modules = {
${tableEntries}
    };
    var __cache = {};
    function __localRequire(id) {
      var key = id.replace(/^\\.\\//, '');
      if (key in __modules) {
        if (__cache[key]) return __cache[key].exports;
        var mod = { exports: {} };
        __cache[key] = mod;
        __modules[key](mod, mod.exports, __localRequire);
        return mod.exports;
      }
      return require(id);
    }
    return __localRequire('./index.js');
  }
});
`

mkdirSync(out, { recursive: true })
writeFileSync(join(out, 'client.js'), bundle)
console.log(`build-client: wrapped ${modules.size} module(s) into lib/client.js`)
