/* dsh-font-settings client bundle (generated by scripts/build-client.mjs) */
window.__ModuleLoader__.load({
  id: "dsh-font-settings",
  factory: function (require) {
    var __modules = {
  "FontCard.js": function (module, exports, require) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.formLabels = formLabels;
    exports.FontCard = FontCard;
    const jsx_runtime_1 = require("react/jsx-runtime");
    const react_1 = require("react");
    const dsh_client_ui_primitives_1 = require("@deepseek-ai/dsh-client-ui-primitives");
    const FontCombobox_1 = require("FontCombobox.js");
    const fonts_1 = require("fonts.js");
    /** SettingsForm 需要的表单文案（rewind 同款结构）。 */
    function formLabels(t) {
        return {
            unavailable: t('unavailable'),
            readOnly: t('readonly'),
            saveFailed: t('saveFailed'),
            save: t('save'),
            saving: t('saving'),
        };
    }
    /**
     * 插件管理页（设置 → 插件 → 字体设置）的配置卡。
     *
     * 表单思路：dsh 的 SettingsFormModel 负责「暂存 → 保存」语义（编辑只改草稿，
     * 保存按钮是草稿落库的唯一入口），SettingsForm 提供外观与状态（只读/保存失败）。
     * 每个字段是 FontCombobox：可搜索的系统字体下拉 + 已设置徽标 + 恢复默认；
     * 各自字段下方一个带「预览」label 的样例块（正文 / 代码），跟随暂存文本
     * 实时刷新；整界面的字体变量也随暂存文本实时应用。
     */
    function FontCard({ t, view, useFontCard, edit, resetField, save, discard }) {
        const state = useFontCard((s) => s);
        if (view === 'summary')
            return null;
        // 实时预览：暂存文本（含尚未保存的输入）即时应用到整界面。
        (0, react_1.useEffect)(() => {
            (0, fonts_1.applyFonts)(state.uiFont.text, state.monoFont.text);
        }, [state.uiFont.text, state.monoFont.text]);
        const uiFont = state.uiFont.text.trim();
        const monoFont = state.monoFont.text.trim();
        return ((0, jsx_runtime_1.jsxs)(dsh_client_ui_primitives_1.SettingsForm, { labels: formLabels(t), state: state, onSave: save, onDiscard: discard, children: [(0, jsx_runtime_1.jsx)(FontCombobox_1.FontCombobox, { id: "font-ui", label: t('uiFontLabel'), placeholder: t('uiFontHint'), text: state.uiFont.text, overridden: state.uiFont.overridden, invalid: state.uiFont.invalid, disabled: !state.writable, overriddenLabel: t('overridden'), resetLabel: t('reset'), invalidLabel: t('invalid'), loadingLabel: t('fontsLoading'), loadFailedLabel: t('fontsLoadFailed'), noMatchLabel: t('noFontMatch'), previewLabel: t('preview'), previewSample: t('previewBody'), previewFontFamily: uiFont ? (0, fonts_1.buildStack)(uiFont, fonts_1.DEFAULT_UI_STACK) : undefined, onReset: () => resetField('uiFont'), onEdit: (text) => edit('uiFont', text) }), (0, jsx_runtime_1.jsx)(FontCombobox_1.FontCombobox, { id: "font-mono", separated: true, label: t('monoFontLabel'), placeholder: t('monoFontHint'), text: state.monoFont.text, overridden: state.monoFont.overridden, invalid: state.monoFont.invalid, disabled: !state.writable, overriddenLabel: t('overridden'), resetLabel: t('reset'), invalidLabel: t('invalid'), loadingLabel: t('fontsLoading'), loadFailedLabel: t('fontsLoadFailed'), noMatchLabel: t('noFontMatch'), previewLabel: t('preview'), previewSample: t('previewCode'), previewFontFamily: monoFont ? (0, fonts_1.buildStack)(monoFont, fonts_1.DEFAULT_MONO_STACK) : undefined, onReset: () => resetField('monoFont'), onEdit: (text) => edit('monoFont', text) })] }));
    }
    
  },
  "FontCombobox.js": function (module, exports, require) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.FontCombobox = FontCombobox;
    const jsx_runtime_1 = require("react/jsx-runtime");
    /**
     * 可搜索字体下拉字段：label + 已设置徽标 + 恢复默认 + 下拉输入 + 预览。
     *
     * 复用 @deepseek-ai/dsh-client-ui-primitives 的 Input（输入框）、Menu
     * （锚定下拉：方向键行走、Enter/Tab 选定、Escape 关闭、外部点击关闭）与
     * Tag（已设置徽标），不手写下拉逻辑。字段视觉对齐 primitives 的
     * SettingsValueField（fields.module.css 的 token 配方：--dsw-alias-* 变量）。
     * 预览块固定位于字段下方，label 为「预览」。
     */
    const react_1 = require("react");
    const dsh_client_ui_primitives_1 = require("@deepseek-ai/dsh-client-ui-primitives");
    const fontCatalog_1 = require("fontCatalog.js");
    const fieldStyle = { display: 'flex', flexDirection: 'column', gap: '6px', padding: '12px 0' };
    const fieldSpacedStyle = {
        ...fieldStyle,
        borderTop: '0.5px solid var(--dsw-alias-border-l2)',
    };
    const headStyle = { display: 'flex', alignItems: 'center', gap: '8px' };
    const labelStyle = {
        flex: 1,
        minWidth: 0,
        fontSize: 13,
        fontWeight: 500,
        lineHeight: 1.5,
        color: 'var(--dsw-alias-label-primary)',
    };
    const badgesStyle = { display: 'inline-flex', alignItems: 'center', gap: '8px' };
    const resetStyle = {
        border: 'none',
        background: 'none',
        padding: 0,
        font: 'inherit',
        fontSize: 12,
        lineHeight: 1.5,
        color: 'var(--dsw-alias-label-secondary)',
        cursor: 'pointer',
    };
    const invalidStyle = {
        margin: 0,
        fontSize: 12,
        lineHeight: 1.5,
        color: 'var(--dsw-alias-state-error-primary)',
    };
    const previewBoxStyle = {
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
        padding: '10px 12px',
        borderRadius: 8,
        border: '1px solid var(--dsw-alias-border)',
        background: 'var(--dsw-alias-surface-raised)',
    };
    const previewLabelStyle = { color: 'var(--dsw-alias-label-tertiary)', fontSize: 12 };
    const previewSampleStyle = { fontSize: 14 };
    /** 一个可搜索字体下拉字段 + 下方预览块。 */
    function FontCombobox(props) {
        const { id, label, text, onReset, onEdit } = props;
        const [open, setOpen] = (0, react_1.useState)(false);
        // null = 加载中；否则为已就绪的列表（空数组 = 枚举失败/无字体）。
        const [fonts, setFonts] = (0, react_1.useState)(null);
        (0, react_1.useEffect)(() => {
            let alive = true;
            (0, fontCatalog_1.loadFonts)().then((list) => {
                if (alive)
                    setFonts(list);
            });
            return () => {
                alive = false;
            };
        }, []);
        const entries = [];
        if (fonts === null) {
            entries.push({ type: 'label', id: 'loading', text: props.loadingLabel });
        }
        else if (fonts.length === 0) {
            entries.push({ type: 'label', id: 'failed', text: props.loadFailedLabel });
        }
        else {
            const matches = (0, fontCatalog_1.filterFonts)(fonts, text);
            if (matches.length === 0) {
                entries.push({ type: 'label', id: 'nomatch', text: props.noMatchLabel });
            }
            else {
                for (const family of matches)
                    entries.push({ id: family, label: family });
            }
        }
        return ((0, jsx_runtime_1.jsxs)("div", { style: props.separated ? fieldSpacedStyle : fieldStyle, children: [(0, jsx_runtime_1.jsxs)("div", { style: headStyle, children: [(0, jsx_runtime_1.jsx)("div", { style: { display: 'flex', alignItems: 'center', gap: '4px', flex: 1, minWidth: 0 }, children: (0, jsx_runtime_1.jsx)("label", { style: labelStyle, htmlFor: id, children: label }) }), props.overridden ? ((0, jsx_runtime_1.jsxs)("span", { style: badgesStyle, children: [(0, jsx_runtime_1.jsx)(dsh_client_ui_primitives_1.Tag, { tone: "neutral", children: props.overriddenLabel }), (0, jsx_runtime_1.jsx)("button", { type: "button", style: resetStyle, disabled: props.disabled, onClick: onReset, children: props.resetLabel })] })) : null] }), (0, jsx_runtime_1.jsx)(dsh_client_ui_primitives_1.Menu, { open: open, anchor: (0, jsx_runtime_1.jsx)(dsh_client_ui_primitives_1.Input, { id: id, value: text, placeholder: props.placeholder, disabled: props.disabled, "aria-invalid": props.invalid || undefined, onFocus: () => setOpen(true), onChange: (event) => onEdit(event.target.value) }), items: entries, selectedId: text.trim() || undefined, onSelect: (family) => {
                        onEdit(family);
                        setOpen(false);
                    }, onClose: () => setOpen(false) }), props.invalid ? (0, jsx_runtime_1.jsx)("p", { style: invalidStyle, children: props.invalidLabel }) : null, (0, jsx_runtime_1.jsxs)("div", { style: previewBoxStyle, children: [(0, jsx_runtime_1.jsx)("span", { style: previewLabelStyle, children: props.previewLabel }), (0, jsx_runtime_1.jsx)("div", { style: { ...previewSampleStyle, fontFamily: props.previewFontFamily }, children: props.previewSample })] })] }));
    }
    
  },
  "FontRow.js": function (module, exports, require) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.FontRow = FontRow;
    const jsx_runtime_1 = require("react/jsx-runtime");
    const react_1 = require("react");
    const constants_1 = require("constants.js");
    const fonts_1 = require("fonts.js");
    const rowStyle = { display: 'flex', flexDirection: 'column', gap: '10px', padding: '4px 0' };
    const fieldLabelStyle = { fontSize: 13, fontWeight: 600 };
    const inputStyle = {
        flex: 1,
        minWidth: 0,
        padding: '4px 8px',
        fontSize: 13,
        borderRadius: 6,
        border: '1px solid var(--dsw-alias-border)',
        background: 'var(--dsw-alias-surface-raised)',
        color: 'var(--dsw-alias-text-primary)',
    };
    const previewStyle = { fontSize: 13 };
    const monoPreviewStyle = { fontSize: 12 };
    const hintStyle = { color: 'var(--dsw-alias-label-tertiary)', fontSize: 12 };
    /** 设置 → 常规 区的「字体」行：界面字体 + 等宽字体，候选目录 + 实时预览。 */
    function FontRow({ t, form }) {
        // 注意：ConfigFormController 的 subscribe/getSnapshot 是普通方法（依赖 this.store），
        // 必须经闭包绑定调用，直接传方法引用会被 React 以 this=undefined 调用而崩溃。
        const snapshot = (0, react_1.useSyncExternalStore)((listener) => form.subscribe(listener), () => form.getSnapshot());
        const settled = snapshot.status === 'ready' && snapshot.value !== undefined;
        const value = settled ? snapshot.value : { uiFont: '', monoFont: '' };
        const [uiFont, setUiFont] = (0, react_1.useState)(value.uiFont);
        const [monoFont, setMonoFont] = (0, react_1.useState)(value.monoFont);
        // 外部变更（宿主重载/其它标签页）回填草稿；不覆盖用户正在输入的值。
        (0, react_1.useEffect)(() => {
            setUiFont(value.uiFont);
            setMonoFont(value.monoFont);
        }, [value.uiFont, value.monoFont]);
        const commitUi = (raw) => {
            const v = raw.trim();
            if (v === (value.uiFont ?? ''))
                return;
            if (v)
                void form.set(constants_1.UI_FONT_FIELD, v);
            else
                void form.unset(constants_1.UI_FONT_FIELD);
        };
        const commitMono = (raw) => {
            const v = raw.trim();
            if (v === (value.monoFont ?? ''))
                return;
            if (v)
                void form.set(constants_1.MONO_FONT_FIELD, v);
            else
                void form.unset(constants_1.MONO_FONT_FIELD);
        };
        const reset = () => {
            setUiFont('');
            setMonoFont('');
            (0, fonts_1.applyFonts)('', '');
            void form.unset(constants_1.UI_FONT_FIELD);
            void form.unset(constants_1.MONO_FONT_FIELD);
        };
        return ((0, jsx_runtime_1.jsxs)("div", { style: rowStyle, children: [(0, jsx_runtime_1.jsx)(FontField, { label: t('uiFontLabel'), hint: t('uiFontHint'), value: uiFont, listId: "dsh-font-settings-ui", catalog: fonts_1.UI_FONT_CATALOG, onChange: (v) => {
                        setUiFont(v);
                        (0, fonts_1.applyFonts)(v, monoFont);
                    }, onCommit: commitUi }), (0, jsx_runtime_1.jsx)(FontField, { label: t('monoFontLabel'), hint: t('monoFontHint'), value: monoFont, listId: "dsh-font-settings-mono", catalog: fonts_1.MONO_FONT_CATALOG, onChange: (v) => {
                        setMonoFont(v);
                        (0, fonts_1.applyFonts)(uiFont, v);
                    }, onCommit: commitMono }), (0, jsx_runtime_1.jsxs)("div", { style: { display: 'flex', flexDirection: 'column', gap: '4px', marginTop: '2px' }, children: [(0, jsx_runtime_1.jsx)("div", { style: { ...previewStyle, fontFamily: (0, fonts_1.buildStack)(uiFont, fonts_1.DEFAULT_UI_STACK) }, children: t('previewUi') }), (0, jsx_runtime_1.jsx)("div", { style: { ...monoPreviewStyle, fontFamily: (0, fonts_1.buildStack)(monoFont, fonts_1.DEFAULT_MONO_STACK) }, children: t('previewMono') }), (0, jsx_runtime_1.jsx)("div", { style: hintStyle, children: t('cjkHint') })] }), (0, jsx_runtime_1.jsx)("div", { children: (0, jsx_runtime_1.jsx)("button", { type: "button", onClick: reset, style: { padding: '4px 12px', fontSize: 13, borderRadius: 6 }, children: t('reset') }) })] }));
    }
    function FontField(props) {
        const { label, hint, value, listId, catalog, onChange, onCommit } = props;
        return ((0, jsx_runtime_1.jsxs)("div", { style: { display: 'flex', flexDirection: 'column', gap: '4px' }, children: [(0, jsx_runtime_1.jsx)("label", { style: fieldLabelStyle, children: label }), (0, jsx_runtime_1.jsxs)("div", { style: { display: 'flex', alignItems: 'center', gap: '8px' }, children: [(0, jsx_runtime_1.jsx)("input", { type: "text", value: value, list: listId, placeholder: hint, spellCheck: false, style: inputStyle, onChange: (e) => onChange(e.target.value), onBlur: (e) => onCommit(e.target.value), onKeyDown: (e) => {
                                if (e.key === 'Enter')
                                    e.target.blur();
                            } }), (0, jsx_runtime_1.jsx)("datalist", { id: listId, children: catalog.map((f) => ((0, jsx_runtime_1.jsx)("option", { value: f }, f))) })] })] }));
    }
    
  },
  "constants.js": function (module, exports, require) {
    "use strict";
    /**
     * 与宿主半侧（src/index.ts）共享的常量。
     *
     * 浏览器半侧刻意不 import 任何 @deepseek-ai 包（客户端 bundle 纯净门禁：
     * 跨插件值导入是构建错误，运行时依赖由浏览器模块表以外部 require 提供）。
     * 因此常量在这里按值复制，改动需两侧同步。
     */
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.MONO_FONT_FIELD = exports.UI_FONT_FIELD = exports.FONT_SETTINGS_NAMESPACE = void 0;
    /** 设置文档命名空间（== 插件条目 id）。 */
    exports.FONT_SETTINGS_NAMESPACE = 'dsh-font-settings';
    /** 界面默认字体字段。 */
    exports.UI_FONT_FIELD = 'uiFont';
    /** 等宽字体字段。 */
    exports.MONO_FONT_FIELD = 'monoFont';
    
  },
  "fontCatalog.js": function (module, exports, require) {
    "use strict";
    /**
     * 系统字体目录：宿主经 Typert Gateway 暴露 `dshFonts/list`
     * （HTTP: POST /api/dshFonts/list，底层 font-list 跨平台枚举：
     * macOS 预编译 CoreText 二进制 / Windows PowerShell / Linux fc-list）。
     *
     * 页面会话内拉取一次并缓存；失败返回空数组（下拉降级为自由输入）。
     */
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.loadFonts = loadFonts;
    exports.filterFonts = filterFonts;
    let rpcSeq = 0;
    let cached = null;
    let inflight = null;
    /** 拉取系统字体族名列表（已去重排序，由宿主完成）。 */
    function loadFonts() {
        if (cached)
            return Promise.resolve(cached);
        inflight ??= (async () => {
            try {
                const res = await fetch('/api/dshFonts/list', {
                    method: 'POST',
                    headers: { 'content-type': 'application/json' },
                    body: JSON.stringify({
                        type: 'client-request',
                        rpcId: `dsh-font-settings-fonts-${++rpcSeq}`,
                        method: 'dshFonts/list',
                        payload: { args: {} },
                    }),
                });
                const json = (await res.json());
                const value = json?.result?.ok === false ? [] : json?.result?.value;
                cached = Array.isArray(value) ? value : [];
            }
            catch {
                cached = [];
            }
            return cached;
        })();
        return inflight;
    }
    /** 按输入过滤：完全命中 → 前缀 → 子串，大小写不敏感，上限 limit 条。 */
    function filterFonts(list, query, limit = 12) {
        const q = query.trim().toLowerCase();
        if (!q)
            return list.slice(0, limit);
        const exact = [];
        const prefix = [];
        const rest = [];
        for (const family of list) {
            const low = family.toLowerCase();
            if (low === q)
                exact.push(family);
            else if (low.startsWith(q))
                prefix.push(family);
            else if (low.includes(q))
                rest.push(family);
        }
        return [...exact, ...prefix, ...rest].slice(0, limit);
    }
    
  },
  "fonts.js": function (module, exports, require) {
    "use strict";
    /**
     * 字体应用：把用户选择接到 DSH 主题变量上。
     *
     * `--dsw-font-family` / `--ds-font-family-code` 由 dsh-client-ui-theme 基础
     * :root 声明；这里用 documentElement 内联样式覆盖（内联样式优先于样式表，
     * 无需 !important）；用户选择为空时移除内联值、回落主题默认。
     */
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.DEFAULT_MONO_STACK = exports.DEFAULT_UI_STACK = void 0;
    exports.buildStack = buildStack;
    exports.applyFonts = applyFonts;
    /** DSH 默认界面字体栈（dsh-client-ui-theme 基础 :root）。 */
    exports.DEFAULT_UI_STACK = '-apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial, sans-serif';
    /** DSH 默认等宽字体栈。 */
    exports.DEFAULT_MONO_STACK = '"SF Mono", "JetBrains Mono", "Fira Code", Consolas, "Liberation Mono", Menlo, Courier, "PingFang SC", "Microsoft YaHei"';
    /** 用户字体前置到默认栈；用户字体缺的字（如生僻汉字）回落到默认栈。 */
    function buildStack(userFont, fallback) {
        const family = userFont.trim().replace(/^["']+|["']+$/g, '');
        if (!family)
            return fallback;
        return `"${family}", ${fallback}`;
    }
    /** 应用到文档根元素。 */
    function applyFonts(uiFont, monoFont) {
        const root = document.documentElement;
        if (uiFont)
            root.style.setProperty('--dsw-font-family', buildStack(uiFont, exports.DEFAULT_UI_STACK));
        else
            root.style.removeProperty('--dsw-font-family');
        if (monoFont)
            root.style.setProperty('--ds-font-family-code', buildStack(monoFont, exports.DEFAULT_MONO_STACK));
        else
            root.style.removeProperty('--ds-font-family-code');
    }
    
  },
  "index.js": function (module, exports, require) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.inject = exports.SETTINGS_NS = void 0;
    exports.apply = apply;
    /**
     * dsh-font-settings —— 浏览器半侧。
     *
     * 绑定宿主设置命名空间 dsh-font-settings（== 插件条目 id），把
     * uiFont / monoFont 应用到 `--dsw-font-family` / `--ds-font-family-code`，
     * 并在插件管理页（设置 → 插件 → 字体设置）提供配置卡。
     *
     * 表单思路（与 rewind 插件同款）：SettingsFormModel 包装 configForms 表单，
     * 「暂存 → 保存」——编辑只改草稿，保存按钮是草稿落库的唯一入口；
     * SettingsForm/SettingsValueField 由 @deepseek-ai/dsh-client-ui-primitives 提供。
     */
    const dsh_client_ui_primitives_1 = require("@deepseek-ai/dsh-client-ui-primitives");
    const FontCard_1 = require("FontCard.js");
    const fonts_1 = require("fonts.js");
    const locales_1 = require("locales.js");
    const constants_1 = require("constants.js");
    /** 本特性设置行的文案命名空间。 */
    exports.SETTINGS_NS = 'settings.font';
    /** 纤维注入：与本特性协作的浏览器插件服务（镜像运行版 ui-theme 客户端）。
     * 0.1.7-rc.1 无 `settingsScope`；configForms 由 ui-settings 客户端提供，
     * 写路径经其 remote.settings 传输。 */
    exports.inject = ['slots', 'locale', 'remote', 'configForms'];
    function apply(ctx) {
        ctx.effect(() => ctx.locale.register(exports.SETTINGS_NS, { zh: locales_1.zh, en: locales_1.en }), 'dsh-font-settings: locales');
        const scope = ctx.configForms.get(constants_1.FONT_SETTINGS_NAMESPACE);
        // 持久值 → 主题变量：每次快照变更应用（含初始 ready）。启动即生效，
        // 与卡内「暂存实时预览」互补——这里是已落库的值，卡里额外跟随草稿。
        ctx.effect(() => {
            const sync = () => {
                const s = scope.getSnapshot();
                if (s.status !== 'ready')
                    return;
                (0, fonts_1.applyFonts)(s.value?.uiFont ?? '', s.value?.monoFont ?? '');
            };
            sync();
            return scope.subscribe(sync);
        }, 'dsh-font-settings: font application');
        // 表单模型：暂存 → 保存。store 供卡组件经 useFontCard 读取。
        const form = new dsh_client_ui_primitives_1.SettingsFormModel(scope, [
            (0, dsh_client_ui_primitives_1.settingsTextField)(constants_1.UI_FONT_FIELD),
            (0, dsh_client_ui_primitives_1.settingsTextField)(constants_1.MONO_FONT_FIELD),
        ]);
        const store = form.bind(() => ({
            ...form.shell(),
            uiFont: form.field(constants_1.UI_FONT_FIELD),
            monoFont: form.field(constants_1.MONO_FONT_FIELD),
        }));
        ctx.effect(() => () => form.dispose(), 'dsh-font-settings: form disposal');
        // 插件管理页（设置 → 插件 → 字体设置）的配置卡：与 rewind 插件同款，
        // key = 包名（插件管理器按包名分发每个 bundle 的配置面）。
        ctx.effect(() => {
            return ctx.slots.inject('plugins.bundle.config', () => ctx.slots.register({
                name: 'plugins.bundle.config',
                key: constants_1.FONT_SETTINGS_NAMESPACE,
                locale: exports.SETTINGS_NS,
                inject: () => ({ hooks: { fontCard: store }, ...form.actions() }),
            }, FontCard_1.FontCard));
        }, 'dsh-font-settings: plugin config card');
    }
    
  },
  "locales.js": function (module, exports, require) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.en = exports.zh = void 0;
    exports.zh = {
        uiFontLabel: '正文字体',
        monoFontLabel: '等宽字体',
        uiFontHint: '正文/界面文字；留空恢复 DSH 默认',
        monoFontHint: '代码/等宽场景字体；留空恢复 DSH 默认',
        preview: '预览',
        previewBody: 'Aa 中文 123 “引号”',
        previewCode: 'const foo = () => “代码”',
        fontsLoading: '正在加载字体列表…',
        fontsLoadFailed: '无法加载字体列表，可直接输入字体名',
        noFontMatch: '没有匹配的字体',
        overridden: '已设置',
        reset: '恢复默认',
        invalid: '输入无效',
        save: '保存',
        saving: '保存中…',
        saveFailed: '保存失败，请重试。',
        unavailable: '该设置当前不可用。',
        readonly: '当前连接为只读，无法保存更改。',
    };
    exports.en = {
        uiFontLabel: 'Body font',
        monoFontLabel: 'Monospace font',
        uiFontHint: 'Body/interface text; empty restores the DSH default',
        monoFontHint: 'Code/monospace text; empty restores the DSH default',
        preview: 'Preview',
        previewBody: 'Aa 中文 123 “quotes”',
        previewCode: 'const foo = () => “code”',
        fontsLoading: 'Loading fonts…',
        fontsLoadFailed: 'Font list unavailable; you can type a font name directly',
        noFontMatch: 'No matching font',
        overridden: 'Overridden',
        reset: 'Reset',
        invalid: 'Invalid input',
        save: 'Save',
        saving: 'Saving…',
        saveFailed: 'Failed to save. Please retry.',
        unavailable: 'This setting is currently unavailable.',
        readonly: 'This connection is read-only; changes cannot be saved.',
    };
    
  },
  "types.js": function (module, exports, require) {
    "use strict";
    /**
     * 浏览器插件契约：优先采用 @deepseek-ai 真实发布的类型（type-only 导入，
     * 编译期擦除，不影响客户端 bundle 纯净性），不足处按运行版代码形状声明。
     * 注意：0.1.7-rc.1 无 `settingsScope` 服务，客户端设置读写走 configForms。
     *
     * 说明：本包 tsconfig.client 用 Node(10) 解析，无法用 exports 子路径
     * `@deepseek-ai/dsh-client-ui-settings/client` 取 ConfigForm 类型，因此基于
     * primitives 的 SettingsFormScope（运行时同构）自行声明；运行版
     * ConfigFormController 满足该形状（getSnapshot/subscribe/mutate）。
     */
    Object.defineProperty(exports, "__esModule", { value: true });
    
  }
    };
    var __cache = {};
    function __localRequire(id) {
      var key = id.replace(/^\.\//, '');
      if (key in __modules) {
        if (__cache[key]) return __cache[key].exports;
        var mod = { exports: {} };
        __cache[key] = mod;
        __modules[key](mod, mod.exports, __localRequire);
        return mod.exports;
      }
      return require(id);
    }
    return __localRequire('./index.js');
  }
});
